services:
  - type: web
    name: crop-disease-predictor
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn CropDiseasePrediction.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: CropDiseasePrediction.settings
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "*"
